import {useEffect,useRef,useState} from 'react';
import {data,view,tel,photo} from '../data';

export function Arrow(){return <svg viewBox="0 0 24 24" width="19" height="19" fill="none" aria-hidden="true"><path d="M4 12h15m-6-6 6 6-6 6" stroke="currentColor" strokeWidth="1.8" strokeLinecap="square"/></svg>}
export function Call({children=data.commercial.cta,secondary=false}:{children?:string;secondary?:boolean}){return <a className={'button '+(secondary?'button-outline':'button-fill')} href={tel()}>{children}<Arrow/></a>}
export function Route({children='Построить маршрут',secondary=true}:{children?:string;secondary?:boolean}){return <a className={'button '+(secondary?'button-outline':'button-fill')} href={data.maps.yandex} target="_blank" rel="noreferrer">{children}<Arrow/></a>}
export function Photo({index,hero=false,className=''}:{index:number;hero?:boolean;className?:string}){return <figure className={'photo '+className}><img src={photo(index)} alt={index===0?'Обслуживание автомобиля':view.photoTitles[index-1]} width="1672" height="941" loading={hero?'eager':'lazy'} fetchPriority={hero?'high':'auto'}/></figure>}
const links=[['Услуги','#services'],['Стоимость','#price'],['Контакты','#contacts']];
export function Header(){const [open,setOpen]=useState(false);const ref=useRef<HTMLButtonElement>(null);useEffect(()=>{const onKey=(event:KeyboardEvent)=>{if(event.key==='Escape'){setOpen(false);ref.current?.focus()}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[]);return <><a className="skip" href="#main">К содержанию</a><header className="header"><a href="#top" className="brand">{data.business.name}<small>{data.business.location.split(',')[0]}</small></a><nav className="desktop-nav" aria-label="Основная навигация">{links.map(([label,href])=><a href={href} key={href}>{label}</a>)}</nav><a className="header-phone" href={tel()}>{data.business.phones[0]}</a><button className="menu-button" ref={ref} aria-expanded={open} aria-controls="mobile-nav" onClick={()=>setOpen(!open)}>{open?'Закрыть':'Меню'}<span aria-hidden="true">{open?'×':'☰'}</span></button></header>{open&&<nav className="mobile-nav" id="mobile-nav" aria-label="Мобильная навигация">{links.map(([label,href])=><a href={href} key={href} onClick={()=>setOpen(false)}>{label}<Arrow/></a>)}<a href={tel()}>{data.business.phones[0]}<Arrow/></a></nav>}</>}
export function Footer(){return <><footer className="footer"><div><strong>{data.business.name}</strong><p>{data.business.address}<br/>{data.business.location}</p></div><div><a className="footer-phone" href={tel()}>{data.business.phones[0]}</a>{data.business.phones.slice(1).map(p=><a className="footer-phone" href={tel(p)} key={p}>{p}</a>)}</div><a href="#top" className="to-top">Наверх ↑</a></footer><div className="mobile-bar"><a href={tel()}>Позвонить</a><a href={data.maps.yandex} target="_blank" rel="noreferrer">Маршрут<Arrow/></a></div></>}
