import { StrictMode, useState } from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";

const base = "/autoservice-demos/koleso98";
const phone = "tel:+79632430003";
const yandex = "https://yandex.ru/maps/?text=Koleso98%20%D0%92%D0%B5%D1%80%D1%85%D0%BD%D1%8F%D1%8F%20%D1%83%D0%BB.%2C%2013%D0%90%20%D0%9A%D0%BE%D0%BB%D1%82%D1%83%D1%88%D0%B8";
const dgis = "https://2gis.ru/spb/search/Koleso98%20%D0%92%D0%B5%D1%80%D1%85%D0%BD%D1%8F%D1%8F%20%D1%83%D0%BB.%2C%2013%D0%90%20%D0%9A%D0%BE%D0%BB%D1%82%D1%83%D1%88%D0%B8";
const services = [["01","Шиномонтаж","Работы с шинами и колёсами. Детали по автомобилю уточните перед приездом."],["02","Ремонт шин и грыж","Осмотр повреждения и ремонт, если восстановление возможно."],["03","Правка и прокатка дисков","Оценка деформации и работы с диском после осмотра."],["04","Вулканизация","Способ ремонта определяется по состоянию шины."],["05","Хранение шин","Сезонное хранение. Наличие места уточняется по телефону."],["06","Утилизация шин","Приём ненужных шин — условия лучше уточнить заранее."]];
const Arrow=()=> <span className="arrow">↗</span>;
function App(){const [open,setOpen]=useState(false);const close=()=>setOpen(false);return <div className="page">
<div className="notice"><span>Колтуши · Верхняя ул., 13А</span><span>Ежедневно 10:00—20:00</span><a href={phone}>+7 (963) 243-00-03</a></div>
<header className="header"><a className="brand" href="#top"><b>98</b><span>Koleso98<small>шины / диски / сервис</small></span></a><nav id="mobile-navigation" className={open?"nav navOpen":"nav"}><a onClick={close} href="#services">Услуги</a><a onClick={close} href="#price">Стоимость</a><a onClick={close} href="#process">Как работаем</a><a onClick={close} href="#contacts">Контакты</a><a className="navPhone" href={phone}>+7 (963) 243-00-03</a></nav><a className="headerCta" href={phone}>Позвонить <Arrow/></a><button className="menu" onClick={()=>setOpen(!open)} aria-label={open?"Закрыть меню":"Открыть меню"} aria-expanded={open} aria-controls="mobile-navigation">{open?"×":"☰"}</button></header>
<main id="top"><section className="hero"><div className="heroGrid"/><div className="heroText"><p className="kicker"><i/> ШИНОМОНТАЖ В КОЛТУШАХ</p><h1>Колесо<br/><em>держит</em><br/>дорогу.</h1><p className="heroLead">Шиномонтаж, ремонт шин и работы с дисками на Верхней улице. Позвоните перед приездом — уточним время и задачу.</p><div className="ctaRow"><a href={phone} className="btn btnBlue">Позвонить <Arrow/></a><a href={yandex} className="btn btnLight" target="_blank" rel="noreferrer">Маршрут <Arrow/></a></div><div className="heroFacts"><div><b>10:00—20:00</b><span>ежедневно</span></div><div><b>Верхняя, 13А</b><span>Колтуши</span></div></div></div><div className="heroPhoto"><img src={`${base}/images/05_koleso98_01.jpg`} alt="шиномонтажа"/><div className="photoCaption"><strong>98 / шины и диски</strong></div><div className="heroStamp"><span>koleso</span><b>98</b><span>колтуши</span></div></div></section>
<section className="marquee"><span>ШИНОМОНТАЖ</span><i>✳</i><span>РЕМОНТ ШИН</span><i>✳</i><span>ПРАВКА ДИСКОВ</span><i>✳</i><span>ВУЛКАНИЗАЦИЯ</span><i>✳</i><span>ХРАНЕНИЕ</span></section>
<section className="section serviceSection" id="services"><div className="sectionHead"><p className="kicker"><i/> НАПРАВЛЕНИЯ РАБОТЫ</p><h2>Когда<br/><em>колесу</em><br/>нужна помощь.</h2><p>Меняем и ремонтируем шины, восстанавливаем диски. Способ ремонта подбираем с учётом состояния колеса.</p></div><div className="serviceList">{services.map(([n,t,d])=><article key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div><Arrow/></article>)}</div></section>
<section className="imageBreak"><div><img src={`${base}/images/05_koleso98_02.jpg`} alt="ремонта шины"/><span>02 / РЕМОНТ ШИН</span></div><div className="imageBreakText"><p className="kicker"><i/> ПО СОСТОЯНИЮ КОЛЕСА</p><h2>Сначала<br/><em>смотрим.</em></h2><p>Повреждение, размер колеса и объём работы влияют на решение. На месте можно оценить шину или диск и согласовать дальнейшие действия.</p><a href={phone} className="underLink">Уточнить по телефону <Arrow/></a></div></section>
<section className="section price" id="price"><div className="pricePanel"><p className="kicker"><i/> СТОИМОСТЬ</p><h2>Стоимость<br/><em>работ.</em></h2><p>Стоимость зависит от размера колеса и необходимых работ. Позвоните, чтобы обсудить замену, ремонт или обслуживание комплекта.</p><a href={phone} className="btn btnBlue">Получить расчёт <Arrow/></a></div><div className="priceAside"><span>ДЛЯ РАСЧЁТА ДОСТАТОЧНО</span><ol><li><b>01</b><div><strong>Размер колеса</strong><p>Назовите маркировку или параметры.</p></div></li><li><b>02</b><div><strong>Что случилось</strong><p>Опишите задачу или повреждение.</p></div></li><li><b>03</b><div><strong>Время приезда</strong><p>Уточните удобное время по телефону.</p></div></li></ol></div></section>
<section className="process section" id="process"><div className="sectionHead"><p className="kicker"><i/> КАК ОБРАТИТЬСЯ</p><h2>Пять шагов<br/><em>до готового</em><br/>колеса.</h2></div><div className="steps">{[["01","Позвоните","Расскажите, какая услуга нужна."],["02","Согласуйте","Уточните время приезда."],["03","Покажите колесо","На месте оценивается состояние."],["04","Уточните стоимость","Детали работы согласуются до начала."],["05","Примите работу","Проверьте результат перед выездом."]].map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
<section className="visuals"><div className="visualTitle"><p className="kicker"><i/> РАБОТА С ШИНАМИ И ДИСКАМИ</p><h2>Детали<br/><em>имеют вес.</em></h2></div><figure className="visualLarge"><img src={`${base}/images/05_koleso98_03.jpg`} alt="восстановления диска"/><figcaption>03 / ДИСКИ</figcaption></figure><figure className="visualSmall"><img src={`${base}/images/05_koleso98_04.jpg`} alt="хранения шин"/><figcaption>04 / ХРАНЕНИЕ</figcaption></figure></section>
<section className="reviews section"><div className="sectionHead"><p className="kicker"><i/> ОТЗЫВЫ</p><h2>Читайте там,<br/><em>где они</em><br/>опубликованы.</h2></div><div className="reviewCard"><span className="sourceDot"/> <small>МНЕНИЯ КЛИЕНТОВ</small><h3>Актуальные мнения — в карточках сервиса.</h3><p>Читайте отзывы о Koleso98 на картах и рассказывайте о своём опыте обслуживания.</p><div><a href={yandex} target="_blank" rel="noreferrer">Яндекс Карты <Arrow/></a><a href={dgis} target="_blank" rel="noreferrer">2ГИС <Arrow/></a></div></div></section>
<section className="faq section"><div className="sectionHead"><p className="kicker"><i/> ЧАСТЫЕ ВОПРОСЫ</p><h2>Перед<br/><em>приездом.</em></h2></div><div className="faqItems"><details open><summary>Нужно ли записываться заранее?<span>+</span></summary><p>Лучше позвонить заранее: так можно уточнить текущую возможность работы и выбрать удобное время.</p></details><details><summary>Как узнать стоимость?<span>+</span></summary><p>Для расчёта сообщите размер колеса и опишите задачу по телефону.</p></details><details><summary>Какие услуги выполняются?<span>+</span></summary><p>Шиномонтаж, ремонт шин и грыж, правка и прокатка дисков, вулканизация, хранение и утилизация шин.</p></details><details><summary>В какое время можно приехать?<span>+</span></summary><p>Работаем ежедневно с 10:00 до 20:00. Перед приездом лучше уточнить время по телефону.</p></details></div></section>
<section className="contact" id="contacts"><div className="contactMain"><p className="kicker"><i/> КАК НАС НАЙТИ</p><h2>Верхняя,<br/><em>13А.</em></h2><p>Колтуши, Ленинградская область.<br/>Ежедневно с 10:00 до 20:00.</p></div><div className="contactInfo"><div><small>ТЕЛЕФОН</small><a href={phone}>+7 (963) 243-00-03</a></div><div><small>АДРЕС</small><strong>Верхняя ул., 13А<br/>Колтуши</strong></div><div className="contactButtons"><a href={phone} className="btn btnBlue">Позвонить <Arrow/></a><a href={yandex} target="_blank" rel="noreferrer" className="btn btnLight">Яндекс Карты <Arrow/></a></div></div><div className="mapBlock"><iframe title="Карта проезда к Koleso98" loading="eager" src="https://yandex.ru/map-widget/v1/?ll=30.633395%2C59.930986&amp;pt=30.633395,59.930986,pm2rdm&amp;z=16" /></div></section></main>
<footer><a className="brand" href="#top"><b>98</b><span>Koleso98<small>Колтуши · Ленинградская область</small></span></a><div><a href="#services">Услуги</a><a href="#contacts">Контакты</a></div><a href={phone}>+7 (963) 243-00-03</a></footer><div className="mobileBar"><a href={phone}>Позвонить</a><a href={yandex} target="_blank" rel="noreferrer">Маршрут</a></div></div>}
createRoot(document.getElementById("root")!).render(<StrictMode><App/></StrictMode>);
