import {useState,useEffect,useRef} from 'react';
import raw from '@site';
export const d=raw as typeof raw & {stamp?:string;stampLabel?:string};
export const phone='tel:'+d.business.phones[0].replace(/[^+\d]/g,'');
export function Arrow(){return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M5 19 19 5M5 5h14v14" stroke="currentColor" strokeWidth="1.7"/></svg>}
export function Call({label=d.commercial.cta,className=''}:{label?:string;className?:string}){return <a className={'button primary '+className} href={phone}>{label}<Arrow/></a>}
export function Route({label='Построить маршрут'}:{label?:string}){return <a className="button secondary" href={d.maps.yandex} target="_blank" rel="noreferrer">{label}<Arrow/></a>}
export function Actions(){return <div className="actions"><Call/><Route/></div>}
export function Photo({index,hero=false,className=''}:{index:number;hero?:boolean;className?:string}){const a=d.visual_assets.assets[index];return <figure className={'photo '+className}><img src={import.meta.env.BASE_URL+'images/'+a.file} alt={index===0?'Работы с автомобилем и колёсами':d.feature[index-1]} width="1672" height="941" loading={hero?'eager':'lazy'} fetchPriority={hero?'high':'auto'}/></figure>}
const nav=[['Услуги','#services'],['Стоимость','#price'],['Контакты','#contacts']];
export function Header(){const [open,setOpen]=useState(false);const ref=useRef<HTMLButtonElement>(null);useEffect(()=>{function key(e:KeyboardEvent){if(e.key==='Escape'){setOpen(false);ref.current?.focus()}}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[]);return <><a className="skip" href="#main">Перейти к содержанию</a><header className="header"><a className="wordmark" href="#top">{d.business.name}<small>{d.business.location.split(',')[0]}</small></a><nav aria-label="Основная навигация">{nav.map(([s,h])=><a key={h} href={h}>{s}</a>)}</nav><a className="header-phone" href={phone}>{d.business.phones[0]}</a><button ref={ref} className="menu-toggle" onClick={()=>setOpen(!open)} aria-expanded={open} aria-controls="mobile-menu" aria-label={open?'Закрыть меню':'Открыть меню'}><span/>{open?'Закрыть':'Меню'}</button></header>{open&&<nav className="mobile-menu" id="mobile-menu" aria-label="Мобильная навигация">{nav.map(([s,h])=><a key={h} href={h} onClick={()=>setOpen(false)}>{s}<Arrow/></a>)}<a href="#faq" onClick={()=>setOpen(false)}>Вопросы и ответы<Arrow/></a><a href={phone}>{d.business.phones[0]}</a></nav>}</>}
export function Footer(){return <><footer className="footer"><strong>{d.business.name}</strong><p>{d.business.location}<br/>{d.address}</p><a href={phone}>{d.business.phones[0]}</a><a href="#top" className="back-top">Наверх ↑</a></footer><div className="mobile-bar"><a href={phone}>Позвонить</a><a href={d.maps.yandex} target="_blank" rel="noreferrer">Маршрут<Arrow/></a></div></>}
