import {data,view,tel} from '../data';
import {Arrow,Call,Photo} from '../components/Shell';

function capitalize(value:string){return value[0].toLocaleUpperCase('ru')+value.slice(1)}
const selected=()=>view.groups?.flatMap(g=>g.items)??data.services.map((_,i)=>i).filter(i=>data.services[i]!=='автосервис');
export function Services(){return <section className="section services" id="services"><div className="section-head"><p className="kicker">Направления работы</p><h2>{view.sectionTitle}</h2><p>{view.sectionLead}</p></div><div className="service-layout"><div className="service-label"><span>01 / Услуги</span><strong>{view.servicesTitle}</strong><a href={tel()}>Спросить по телефону <Arrow/></a></div>{view.groups?<div className="service-groups">{view.groups.map(group=><div className="service-group" key={group.title}><h3>{group.title}</h3><ul>{group.items.map(i=><li key={i}>{capitalize(data.services[i])}</li>)}</ul></div>)}</div>:<ol className="service-rows">{selected().map((i,n)=><li key={i}><span>{String(n+1).padStart(2,'0')}</span><h3>{capitalize(data.services[i])}</h3><a href={tel()} aria-label={'Уточнить '+data.services[i]}><Arrow/></a></li>)}</ol>}</div></section>}
export function Details(){return <section className="details" id="details"><div className="details-heading"><p className="kicker">Подробнее</p><h2>{view.detailTitle}</h2></div>{[1,2,3].map((index)=><article className={'detail detail-'+index} key={index}><Photo index={index}/><div className="detail-copy"><span className="detail-num">0{index} / 03</span><h3>{view.photoTitles[index-1]}</h3><p>{view.photoText[index-1]}</p><a href={tel()} className="text-link">Уточнить по телефону <Arrow/></a></div></article>)}</section>}
export function Process(){const mobile=['forvater','krauch','tiretech'].includes(import.meta.env.VITE_SITE||'forvater');return <section className="section process" id="process"><div><p className="kicker">Как обратиться</p><h2>{mobile?'Начните с места и проблемы.':'Начните с симптома.'}</h2><p>Короткий разговор по телефону поможет определить, какие данные нужны для обслуживания.</p></div><ol><li><span>01</span><strong>Опишите задачу</strong><p>{mobile?'Где находится автомобиль, что случилось с колесом и какой у него размер.':'Марка и модель автомобиля, признаки неисправности и желаемая работа.'}</p></li><li><span>02</span><strong>Уточните возможность</strong><p>{mobile?'Спросите о выезде по вашему адресу и доступности нужного вида работ.':'Обсудите время приёма, необходимость осмотра и доступность услуги.'}</p></li><li><span>03</span><strong>Согласуйте детали</strong><p>Уточните ориентир по стоимости и времени до начала работ.</p></li></ol></section>}
export function PriceAndFaq(){const q=[['Как узнать стоимость?','Стоимость зависит от автомобиля и объёма работ. Позвоните нам, чтобы обсудить вашу задачу.'],['Когда можно обратиться?',data.business.hours+'. Перед поездкой или запросом на выезд уточните доступность приёма.'],['Какие данные назвать при звонке?','Назовите марку и модель автомобиля, опишите задачу. Для работ с колесом подготовьте его размер.'],['Можно ли сразу записаться?', 'Позвоните по указанному номеру и уточните удобное время.']];return <><section className="section price" id="price"><div><p className="kicker">Стоимость</p><h2>Расчёт начинается с вашей задачи.</h2></div><div><p>Стоимость зависит от автомобиля, характера неисправности и объёма работ. Позвоните нам, чтобы обсудить ремонт или обслуживание.</p><Call>Уточнить стоимость</Call></div></section><section className="section faq" id="faq"><div><p className="kicker">Коротко о важном</p><h2>Перед обращением</h2></div><div className="faq-list">{q.map(([question,answer])=><details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></section></>}
