import {data,view,tel} from '../data';
import {Arrow,Call,Photo} from '../components/Shell';

function capitalize(value:string){return value[0].toLocaleUpperCase('ru')+value.slice(1)}
const selected=()=>view.groups?.flatMap(g=>g.items)??data.services.map((_,i)=>i).filter(i=>data.services[i]!=='автосервис');
export function Services(){return <section className="section services" id="services"><div className="section-head"><p className="kicker">Направления работы</p><h2>{view.sectionTitle}</h2><p>{view.sectionLead}</p></div><div className="service-layout"><div className="service-label"><span>01 / Услуги</span><strong>{view.servicesTitle}</strong><a href={tel()}>Записаться <Arrow/></a></div>{view.groups?<div className="service-groups">{view.groups.map(group=><div className="service-group" key={group.title}><h3>{group.title}</h3><ul>{group.items.map(i=><li key={i}>{capitalize(data.services[i])}</li>)}</ul></div>)}</div>:<ol className="service-rows">{selected().map((i,n)=><li key={i}><span>{String(n+1).padStart(2,'0')}</span><h3>{capitalize(data.services[i])}</h3><a href={tel()} aria-label={'Записаться: '+data.services[i]}><Arrow/></a></li>)}</ol>}</div></section>}
export function Details(){return <section className="details" id="details"><div className="details-heading"><p className="kicker">Подробнее</p><h2>{view.detailTitle}</h2></div>{(data.business.name==='Forvater'?[1,2]:[1,2,3]).map((index)=><article className={'detail detail-'+index} key={index}><Photo index={index}/><div className="detail-copy"><span className="detail-num">0{index} / {data.business.name==='Forvater'?'02':'03'}</span><h3>{view.photoTitles[index-1]}</h3><p>{view.photoText[index-1]}</p><a href={tel()} className="text-link">{data.commercial.cta} <Arrow/></a></div></article>)}</section>}
export function Process(){const c=data.commercial;if(!c.steps.length)return null;return <section className="section process" id="process"><div><p className="kicker">Перед обращением</p><h2>{c.processTitle}</h2><p>{c.processLead}</p></div><ol>{c.steps.map(([title,text],i)=><li key={title}><span>0{i+1}</span><strong>{title}</strong><p>{text}</p></li>)}</ol></section>}
export function PriceAndFaq(){const c=data.commercial;return <><section className="section price" id="price"><div><p className="kicker">Запись и стоимость</p><h2>{c.priceTitle}</h2></div><div><p>{c.priceText}</p><Call>Узнать стоимость</Call></div></section><section className="section faq" id="faq"><div><p className="kicker">Полезно перед визитом</p><h2>{c.faqTitle}</h2></div><div className="faq-list">{c.faq.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section></>}
